// Act library — all animals in humane, sanctuary or positive-reinforcement contexts only.
const ACTS = [
  {
    id: "elephant_walk",
    name: "Elephant Sanctuary Walk",
    type: "animal_education",
    animals: ["elephant"],
    political_valence: -0.35,
    entertainment_radius: 0.50,
    description: "Gentle giants roam freely through a naturalistic habitat while rangers narrate their stories.",
    age_friendly: true,
    phone_suppressor: 0.88,
    emoji: "🐘",
  },
  {
    id: "tiger_habitat",
    name: "Tiger Habitat Walkthrough",
    type: "animal_education",
    animals: ["tiger"],
    political_valence: -0.30,
    entertainment_radius: 0.48,
    description: "Walk glass-side through a conservation habitat; rangers share rewilding success stories.",
    age_friendly: true,
    phone_suppressor: 0.85,
    emoji: "🐯",
  },
  {
    id: "environmental_story",
    name: "Environmental Storytelling",
    type: "storytelling",
    animals: [],
    political_valence: -0.50,
    entertainment_radius: 0.45,
    description: "A theatrical journey through climate change, told via projection mapping and live narration.",
    age_friendly: true,
    phone_suppressor: 0.80,
    emoji: "🌍",
  },
  {
    id: "multicultural_dance",
    name: "Multicultural Dance Revue",
    type: "performance",
    animals: [],
    political_valence: -0.20,
    entertainment_radius: 0.55,
    description: "Performers from six continents share traditional and contemporary dance forms.",
    age_friendly: true,
    phone_suppressor: 0.82,
    emoji: "💃",
  },
  {
    id: "science_illusion",
    name: "Science Illusion Show",
    type: "education",
    animals: [],
    political_valence: -0.15,
    entertainment_radius: 0.60,
    description: "Dazzling demonstrations of physics and chemistry disguised as magic — audience learns without knowing it.",
    age_friendly: true,
    phone_suppressor: 0.90,
    emoji: "🔬",
  },
  {
    id: "aerial_trapeze",
    name: "Aerial Trapeze",
    type: "acrobatics",
    animals: [],
    political_valence: 0.00,
    entertainment_radius: 0.65,
    description: "High-flying artistry and breathtaking catches 30 metres above the ring.",
    age_friendly: true,
    phone_suppressor: 0.95,
    emoji: "🎪",
  },
  {
    id: "juggling",
    name: "Juggling & Skill Display",
    type: "skill",
    animals: [],
    political_valence: 0.00,
    entertainment_radius: 0.70,
    description: "World-champion jugglers push the limits of balance, reaction, and craft.",
    age_friendly: true,
    phone_suppressor: 0.88,
    emoji: "🤹",
  },
  {
    id: "contemporary_clown",
    name: "Contemporary Clown Spectacular",
    type: "comedy",
    animals: [],
    political_valence: -0.10,
    entertainment_radius: 0.58,
    description: "Physical comedy and absurdist humour that crosses every boundary — except mean-spiritedness.",
    age_friendly: true,
    phone_suppressor: 0.87,
    emoji: "🤡",
  },
  {
    id: "magic_illusion",
    name: "Magic & Grand Illusion",
    type: "magic",
    animals: ["dove"],
    political_valence: 0.05,
    entertainment_radius: 0.62,
    description: "Classic stage illusions updated for a modern audience; doves released to the rafters, never caged.",
    age_friendly: true,
    phone_suppressor: 0.91,
    emoji: "🎩",
  },
  {
    id: "contortion_art",
    name: "Contortion Art",
    type: "acrobatics",
    animals: [],
    political_valence: -0.10,
    entertainment_radius: 0.50,
    description: "The human body as sculpture — a meditative blend of flexibility and artistic expression.",
    age_friendly: true,
    phone_suppressor: 0.83,
    emoji: "🧘",
  },
  {
    id: "liberty_horses",
    name: "Liberty Horse Ballet",
    type: "animal_education",
    animals: ["horse"],
    political_valence: 0.20,
    entertainment_radius: 0.52,
    description: "Horses move freely without riders, responding to subtle cues in a dance trained entirely with positive reinforcement.",
    age_friendly: true,
    phone_suppressor: 0.86,
    emoji: "🐴",
  },
  {
    id: "family_comedy",
    name: "Family Comedy Hour",
    type: "comedy",
    animals: [],
    political_valence: 0.10,
    entertainment_radius: 0.65,
    description: "Clean, wholesome stand-up and sketch comedy the whole family can watch together.",
    age_friendly: true,
    phone_suppressor: 0.84,
    emoji: "😄",
  },
  {
    id: "marching_band",
    name: "Grand Marching Band Parade",
    type: "music",
    animals: [],
    political_valence: 0.30,
    entertainment_radius: 0.55,
    description: "A 60-piece brass band marches through the big top in a rousing celebration of American musical heritage.",
    age_friendly: true,
    phone_suppressor: 0.80,
    emoji: "🎺",
  },
  {
    id: "acrobatic_troupe",
    name: "International Acrobatic Troupe",
    type: "acrobatics",
    animals: [],
    political_valence: 0.05,
    entertainment_radius: 0.68,
    description: "Elite gymnasts from twelve countries perform synchronized human towers and tumbling sequences.",
    age_friendly: true,
    phone_suppressor: 0.92,
    emoji: "🤸",
  },
  {
    id: "patriotic_finale",
    name: "Patriotic Finale Spectacular",
    type: "celebration",
    animals: [],
    political_valence: 0.40,
    entertainment_radius: 0.48,
    description: "A stirring Americana celebration — flags, fanfares, and community spirit close out the night.",
    age_friendly: true,
    phone_suppressor: 0.75,
    emoji: "🎆",
  },
];

// Lookup by id
const ACT_BY_ID = Object.fromEntries(ACTS.map(a => [a.id, a]));

// Unique animals featured across all acts
const ANIMAL_ROSTER = [...new Set(ACTS.flatMap(a => a.animals))];
